version: '3'
services:
  cc:
    build: ./
    image: card-collection
    working_dir: /usr/src/app/card-collection
    environment:
      - "NEXT_WEBPACK_USEPOLLING=1"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    command: yarn dev
    depends_on:
      - postgres
    networks:
      - cc-network

  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: app_dev
      POSTGRES_PASSWORD: dev_password
      ALLOW_IP_RANGE: "172.0.0.0/8"
    command: ["postgres", "-c", "log_statement=none"]
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - cc-network

networks:
  cc-network:

volumes:
  pgdata:

